### ISSUE TITLE
TODO example crash if action "addTask" is deleted

### ISSUE THREAD

**Issue by vincent-hui** [benlau/quickflux#16]
I deleted action "addTask" and corresponding code fragment and then I build the example and run, todo example program crashes immediately. I use master branch. OS is Windows 10.
in ActionTypes.qml
//property string addTask;
in Footer.qml
//AppActions.add(textField.text);
in TodoStore.qml
//    Filter {
//        // Filter - Add a filter rule to parent

//        // Filter item listens on parent's dispatched signal,
//        // if a dispatched signal match with its type, it will
//        // emit its own "dispatched" signal. Otherwise, it will
//        // simply ignore the signal.

//        type: ActionTypes.addTask
//        onDispatched: {
//            var item = {
//                uid: nextUid++,
//                title: message.title,
//                done: false
//            }
//            model.append(item);
//        }
//    }

**Comment by benlau** [comment]
hi @vincent-hui,

Are you using Qt 5.8? I think it is a bug of QML Caching. It is cached in your first time execution. Then you remove a property in ActionTypes and refer it in somewhere else. You may try to remove all the cache or disable the cache completely by set QML_DISABLE_DISK_CACHE to true.

Example
```
int main(int argc, char *argv[])
{
    qputenv("QML_DISABLE_DISK_CACHE", "true");

    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));

    return app.exec();
}

```

**Comment by vincent-hui** [comment]
yes, I am using Qt 5.8
My program does not crash if   QML_DISABLE_DISK_CACHE is set to true.

Thank a lot.
