### ISSUE TITLE
[Usage Question] Deserializing an var from a store

### ISSUE THREAD

**Issue by jordanbaucke** [benlau/quickflux#17]
I have a Store for my view `View1Store.qml`
```
Store {
    property var view1Object // moved to store from `view1.qml`
    Filter {
        type: ActionTypes.loadViewItems
        onDispatched: {
            view1Object = message.viewItem
    }
}
```
And I want to serialize it into a JSON to be rendered in a qml `TextArea` in my `View1.qml`
```
    TextArea {
        id: recordView
        anchors{
            top: parent.top
            topMargin: 10
            left: parent.left
            leftMargin: 20
        }
        width: 200
        height: 400
        clip: true
        readOnly: true
        textFormat: TextEdit.AutoText
        text: JSON.stringify(MainStore.view1store.view1Object) // ??? 
    }
```
Am I not thinking about this correctly?

Previously when I was loading the view, I used: 

```
stack.push(view1, { view1Object: item })
```
which assigned `property var view1Object` in `view1.qml` and I could just do: 

```
    onView1ObjectChanged: {
        recordView.text = JSON.stringify(view1Object, null, 2)
     }
```
I believe I am thinking about this the wrong way in how the view should be related to the store

**Comment by benlau** [comment]
HI,

What are you worrying? I may not understand your question correctly. Basically, the method 1 is already a straightforward method. It should works pretty well in QML.

Method 2, pushing the store property (?) into a new view, it will lost the data binding and therefore will not be updated on property changes.

**Comment by jordanbaucke** [comment]
@benlau 

In "Method 1", I'm getting:

```qrc:/views/EView1.qml:58:15: Unable to assign [undefined] to QString```

Which is the line:

```text: JSON.stringify(MainStore.view1store.view1Object) ```

**Comment by benlau** [comment]
hmmm..

Could you try to add following lines in your source code , and what is the result?:

```
Component.onCompleted {
     console.log(MainStore.view1store);
     console.log(MainStore.view1store.view1Object);
     console.log(JSON.stringify(Hydrate.dehydrate(MainStore)));
}
```

**Comment by jordanbaucke** [comment]
```
qml: EView1Store_QMLTYPE_61(0x7fd71bcaaf40)
qml: undefined
qml: {"history":{"history":[{}],"historyCursor":0,"nextBtnEnabled":false,"prevBtnEnabled":false},"view0store":{"_lobbiesModel":{"count":0,"dynamicRoles":false,"idAttribute":"id"},"_usersModel":{"count":0,"dynamicRoles":false,"idAttribute":"id"},"history_lobbies_page":0,"history_users_page":0,"nextBtnEnabled":false,"prevBtnEnabled":false},"view1store":{"_userFriends":{"count":0,"data":[],"dynamicRoles":false},"_userLobbiesModel":{"count":0,"dynamicRoles":false,"idAttribute":"id"}}}
```

**Comment by benlau** [comment]
@jordanbaucke ,

The second and third line show that `view1object` is missing in view1store. 

Are you using Qt 5.8/5.9 with QML cache? If yes, then I guess the cache is not updated. You may try to remove "*.qmlc" or set QML_DISABLE_DISK_CACHE to true 

For example:

```
int main(int argc, char *argv[])
{
    qputenv("QML_DISABLE_DISK_CACHE", "true");

    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));

    return app.exec();
}
```

**Comment by jordanbaucke** [comment]
@benlau - Qt 5.6.2 (so that could be the problem!)

**Comment by jordanbaucke** [comment]
@benlau ,

I figured it out:

```
    property var view1Object: new Object
```
