### ISSUE TITLE
todo example no longer works with 5.9.1 

### ISSUE THREAD

**Issue by clogwog** [benlau/quickflux#19]
Hi Ben,  

i still have an older version of quickflux (commit 65d79cfedf61ca0a071cb528e09280af494f9e0b)  and the todo app still adds new entries there (using 5.9.1, on osx ) but the new version of the todo example doesn't do anything when i check off items or enter new items in the list and press the "Add" button.
 
is this a known issue ? or has something broken with the latest version of Qt ?

let me know if it is a new issue and i can collect more details if you need them, otherwise let me know and i'll delete this issue. don't want to double up. (i searched but didn't see any other report like this)

thanks,
tom

**Comment by benlau** [comment]
hi @clogwog ,

Thanks for reporting. I have checked the example program and found that it is a silly mistake caused by one of the middleware. I have just committed a fix. If you still have any problem, please feel free to contact me.
