### ISSUE TITLE
how to use dispatcher from cpp with parameters?

### ISSUE THREAD

**Issue by alexodus** [benlau/quickflux#4]
```
QQmlApplicationEngine engine;
engine.load(QUrl(QStringLiteral("qrc:/main.qml")));
...
QFAppDispatcher* dispatcher = QFAppDispatcher::instance(&engine);

//dispatch action without parameters
dispatcher->dispatch("actionWithoutParameters"); //OK

//dispatch action with parameters
QJSEngine myEngine;
QJSValue myObject = myEngine.newObject();
myObject.setProperty("parameter1","value1");
myObject.setProperty("parameter2","value2");
dispatcher->dispatch("actionWithParameters",myObject); //KO

```
the error is:

> JSValue can't be reassigned to another engine.

**Comment by benlau** [comment]
You could set the property of a QJSValue by : 

```
myObject.setProperty("parameter1", myEngine.toScriptValue<QVariant>("value1));
myObject.setProperty("parameter2", myEngine.toScriptValue<QVariant>("value1));
```

Example:

[quickflux/qfsignalproxy.cpp at master · benlau/quickflux](https://github.com/benlau/quickflux/blob/master/priv/qfsignalproxy.cpp#L77)

The convention code is not exported to public yet, I will include it in next release.

**Comment by benlau** [comment]
Quick Flux 1.0.5 has been released. And now it support to dispatch message with type of QVariant in C++ side.

[Release v1.0.5 Release · benlau/quickflux](https://github.com/benlau/quickflux/releases/tag/v1.0.5)
