### ISSUE TITLE
QuickFlux for Application vs QmlComponent Library

### ISSUE THREAD

**Issue by TanNgocDo** [benlau/quickflux#5]
Hi Benlau,

Sorry for the easy misunderstanding title . I want to mention to applying QuickFlux to Qml Application vs the QmlComponent user defined for reusing. 
It seems  QuickFlux is not suitable for QmlComponent library. For example: I want to write some customized button and re-use it in a lot of different Qml Application. I always need to expose the signal API and can not use the central Dispatcher in this case. 
So, do you think for each QmlApplication we should defined one ActionTypes and one Central Dispatch ?
For some reusable QmlComponent we still need to use signal and slot.

Please let me know your opinion!

Thank you!

**Comment by benlau** [comment]
Hi @TanNgocDo ,

In my opinion, as a library component, it usually not involve complex message flow / signal propagation. The event source(e.g a button) and receiver (who should response for making animation effect) within a library should be close.  Dispatcher may not offer advantage over traditional signal and slot in this case. Therefore, when I design QuickFlux, I don't consider to let it be able to be used within another library. It is more like an application architecture framework.

**Comment by TanNgocDo** [comment]
Thanks for your explanation :)
