### ISSUE TITLE
Does store always need to be a singleton qml component

### ISSUE THREAD

**Issue by TanNgocDo** [benlau/quickflux#6]
Hi,

I see your examples of quickflux. You always use Store as a singleton component.
Is there any reason for this ? I guess that you want singleton component "listen" on the "dispatched" signal of AppListener. If there are **more than one** qml component, is it ' difficult to handle the "slot" ?
Because we're using only one central dispatcher .

Please let me know if i'm wrong.

Thank you!

**Comment by benlau** [comment]
> Is there any reason for this ?

Because singleton stores could avoid to pass data from top level component to bottom component. It is quite troublesome if it need to pass data across several components.

> If there are more than one qml component,  is it ' difficult to handle the "slot" ?

Do you mean to have more than one store to listen on the same action? From my experience, it is not different to handle it.

**Comment by TanNgocDo** [comment]
> Do you mean to have more than one store to listen on the same action? From my experience, it is not different to handle it.

Hi, I mean this assumption: one Qml component we don't define it as a component
In that component we're have some handle some dispatched signal like : "openWindow"
And because the component is not a singleton so, there are many places use many "instances" of that component.
What will happen if the user call central dispatcher to dispatch "openWindow"?
Which "instances" will receipt that signal ? 
In this case I think we need to manage the "id" for each "instance" and each instance needs to check whether that dispatched signal belonged to it.

**Comment by benlau** [comment]
> What will happen if user calls central dispatcher to dispatch "openWindow"?

Then all the instance of AppListener will receive the signal. That is fine for most of the case. Basically, the processor nowadays is fast enough to handle it. However, if you have a Repeater/ListView with 1k of items, and you have AppListener in the delegate component. Then probably you will in trouble. 

So I would suggest to avoid using AppListener in delegate component. Instead, you may use it with the model object. And manipulate the model data directly.

**Comment by TanNgocDo** [comment]
Thank you. I will consider this.
